### ISSUE TITLE
Leave a link to the video

### ISSUE THREAD

**Issue by YarikTH** [matheusgomes28/cmake-cpp-modules#1]
I'm here from the recent video [Modules in C++ 20 - Thoughts on Compiler & CMake Support](https://youtu.be/UkDGVb0QXMs).

It has a lot of useful info that this repository doesn't have. How about adding link to it in the readme, so anyone that sees this repository can check it?

**Comment by matheusgomes28** [comment]
Thanks for the suggestion, I can add a link and clean up the readme a little bit 😄

**Comment by matheusgomes28** [comment]
Added the link and made some other improvements to `README.md`, so I'll be closing this.

I think I'm going to add better code for representation in this repo. Don't want to just have an identic copy of the code in the Kitware example 🖨️  Plus, I think it could benefit from having some templated code and new C++20 features in `my_lib` to make sure compilation is working fine for whoever is trying to use this as a skeleton project.
